name: CI

on:
  push:
    branches:
      - main

  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build artifact
        run: cargo build --verbose

      - name: Test artifact
        run: cargo test --verbose
